### PR TITLE
updated function names

### PR DESCRIPTION
**Pull request by pena060**
Renamed functions to reflect what their purpose is:

Input() -> GetUserInput()
update() -> UpdatePosition()
draw() -> UpdateScreen()
text_buffer -> PrintToWindow()

### CODE REVIEW

**Comment by etzl** [comment]
Hey @pena060 thanks for the patch. When building with your new changes I got the following error:

```make
src/bullet.cpp:9:6: error: no declaration matches ‘bool Bullet::UpdatePositions()’
    9 | bool Bullet::UpdatePositions()
      |      ^~~~~~
```

This is probably because the `bullet.hpp` file hasn't been updated

**Comment by pena060** [comment]
> Hey @pena060 thanks for the patch. When building with your new changes I got the following error:
> 
> ```makefile
> src/bullet.cpp:9:6: error: no declaration matches ‘bool Bullet::UpdatePositions()’
>     9 | bool Bullet::UpdatePositions()
>       |      ^~~~~~
> ```
> 
> This is probably because the `bullet.hpp` file hasn't been updated

You are correct I will fix that right away!

Edit: I have updated bullet.hpp

**Review by etzl — COMMENTED** [review]
I got the following error:

```make
src/gamemanager.cpp:169:16: error: ‘class Bullet’ has no member named ‘update’
  169 |         if (p->update())
      |                ^~~~~~
```

If it's possible, consider building the project, I've updated [contributing guideline](https://github.com/etzl/among-stars/blob/develop/CONTRIBUTING.md). By the way, are using an IDE?

**Comment by pena060** [comment]
It seems like the github app isnt pushing all my changes. Let me see what I
can do.

**Comment by pena060** [comment]
it seems im having issues with visual studio compiling the project, it does not detect the project. the issue should be fixed by changing UpdatePositions() on bullet.cpp and bullet.hpp back to update() since that wasnt meant to be changed . I did that by mistake. 

I closed the pull request because since my visual studio is having issues detecting the project for compiling I cant properly test the code. sorry about that.

**Pull request closed without merging**
